version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:13.8.0

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: npm run lint 

  test:
    executor: my-executor
    steps:
      - checkout
      - run: npm run test


  analyze:
    executor: my-executor
    steps:
      - checkout
      - run: npm audit

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test